### ISSUE TITLE
error in internet explorer

### ISSUE THREAD

**Issue by zuomingcai** [locoslab/vue-typescript-component#5] opened 2016-11-11 09:16 UTC
![image](https://cloud.githubusercontent.com/assets/13760662/20210053/8ef0b2d8-a832-11e6-91d9-999b8b62318c.png)

**Comment by locobert** [comment] 2016-11-12 15:55
Please provide an English error message and an example project

**Comment by zuomingcai** [comment] 2016-11-14 01:25
english message:Object.getPrototypeOf:'this' **is not** Object.
I will provider an example project later.

**Comment by locobert** [comment] 2016-11-14 07:02
It works for me with the project you provided in #4. If this is for different code, please provide an example.

**Comment by zuomingcai** [comment] 2016-11-14 15:38
example project is attached.

[build.zip](https://github.com/locoslab/vue-typescript-component/files/589699/build.zip)
[test.zip](https://github.com/locoslab/vue-typescript-component/files/589700/test.zip)

**Comment by locobert** [comment] 2016-11-15 09:02
Thanks. I could reproduce the issue and will look into it

**Comment by locobert** [comment] 2016-11-20 09:54
Fixed in 0.6.1. Please reopen, if issue persists.

**Closed as completed by locobert** 2016-11-20 09:54 UTC

**Comment by zuomingcai** [comment] 2016-12-21 12:19
it now works on ie11,but still not work on ie9，
obj[n].__proto__.constructor throw an error,because in ie9,obj[n].__proto__ return [undefined] when obj[n] return a string.

**Comment by locobert** [comment] 2016-12-28 20:36
Since IE9 has reached end-of-life quite some time ago, we do not target it (or even have it). However, if you can provide a pull request with an easily maintainable fix, I am happy to include it.

**Comment by zuomingcai** [comment] 2016-12-30 05:24
I have changed the code : 
props[n].type =obj[n]. __ proto __ .constructor;
to:
props[n].type =obj[n]. __ proto __ ? obj[n].__ proto __.constructor:obj[n].constructor;

and it works fine now in IE9.

**Comment by locobert** [comment] 2017-01-04 21:38
Thanks!

Added in 0.6.2
